name: Deploy Lambda Infrastructure (CFT)
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment to deploy"
        required: true
        type: choice
        options:
          - dev
          - qa

permissions:
  id-token: write
  contents: read

jobs:
  deploy-infra:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy Lambda Infrastructure using CloudFormation
        run: |
          ENV=${{ github.event.inputs.environment }}
          STACK_NAME="emerald-on-prem-stack-${ENV}"
          aws cloudformation deploy \
            --template-file cft.yaml \
            --stack-name $STACK_NAME \
            --parameter-overrides Environment=$ENV \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Get Lambda Function URL
        run: |
          ENV=${{ github.event.inputs.environment }}
          STACK_NAME="emerald-on-prem-stack-${ENV}"
          aws cloudformation describe-stacks \
            --stack-name $STACK_NAME \
            --query "Stacks[0].Outputs" \
            --output table

