name: Lambda CI & Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      env:
        description: "Select environment"
        required: true
        type: choice
        options:
          - dev
          - qa

permissions:
  contents: read
  id-token: write

jobs:
  ci-checks:
    name: Run Prettier, ESLint, License
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install linting tools
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier check
        run: npm run format



  deploy:
    name: Deploy to AWS Lambda
    needs: ci-checks
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Deploy to Lambda
        run: |
          ENV=${{ github.event.inputs.env || 'dev' }}
          if [ "$ENV" = "dev" ]; then
            cd lambda/dev
            zip -r function.zip .
            aws lambda update-function-code \
              --function-name mynodedev \
              --zip-file fileb://function.zip
          else
            cd lambda/qa
            zip -r function.zip .
            aws lambda update-function-code \
              --function-name mynodes3bucket \
              --zip-file fileb://function.zip
          fi
